name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'razia'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello World razia
        run: echo "Hello ${{ github.event.inputs.name }}"
